name: "Podcast Generator"
author: "Rutwij Patankar"
description: "Generates a feed for podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email: 
    description: "Email of user running commit"
    required: true
    default: ${{github.actor}}@localhost
  name:
    description: "Name of user running commit"
    required: true
    default: ${{github.actor}}@localhost