name: generate-podcast-feed
on: [push]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: rutw1j/linkedin-learning-practical-github-actions/podcast-generator@main
